/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { VideoBlockListRelationFilter } from "../../videoBlock/base/VideoBlockListRelationFilter";
import { ImageBlockListRelationFilter } from "../../imageBlock/base/ImageBlockListRelationFilter";
import { TextBlockListRelationFilter } from "../../textBlock/base/TextBlockListRelationFilter";

@InputType()
class PageWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => VideoBlockListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VideoBlockListRelationFilter)
  @IsOptional()
  @Field(() => VideoBlockListRelationFilter, {
    nullable: true,
  })
  videoBlocks?: VideoBlockListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ImageBlockListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ImageBlockListRelationFilter)
  @IsOptional()
  @Field(() => ImageBlockListRelationFilter, {
    nullable: true,
  })
  imageBlocks?: ImageBlockListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TextBlockListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TextBlockListRelationFilter)
  @IsOptional()
  @Field(() => TextBlockListRelationFilter, {
    nullable: true,
  })
  textBlocks?: TextBlockListRelationFilter;
}

export { PageWhereInput as PageWhereInput };
